connect admin_usuarios/admin_usuarios

update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 1;
update comentario set texto = 'Aenean lectus.'where comentario_id= 2;
update comentario set texto = 'Donec quis orci eget orci vehicula condimentum.'where comentario_id= 3;
update comentario set texto = 'Sed sagittis.'where comentario_id= 4;
update comentario set texto = 'Fusce posuere felis sed lacus.'where comentario_id= 5;
update comentario set texto = 'In eleifend quam a odio.'where comentario_id= 6;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 7;
update comentario set texto = 'Nulla mollis molestie lorem.'where comentario_id= 8;
update comentario set texto = 'Vivamus in felis eu sapien cursus vestibulum.'where comentario_id= 9;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 10;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 11;
update comentario set texto = 'Proin interdum mauris non ligula pellentesque ultrices.'where comentario_id= 12;
update comentario set texto = 'Nulla tellus.'where comentario_id= 13;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 14;
update comentario set texto = 'Duis consequat dui nec nisi volutpat eleifend.'where comentario_id= 15;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 16;
update comentario set texto = 'Pellentesque viverra pede ac diam.'where comentario_id= 17;
update comentario set texto = 'Vivamus vestibulum sagittis sapien.'where comentario_id= 18;
update comentario set texto = 'Praesent blandit.'where comentario_id= 19;
update comentario set texto = 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'where comentario_id= 20;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 21;
update comentario set texto = 'Aliquam quis turpis eget elit sodales scelerisque.'where comentario_id= 22;
update comentario set texto = 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'where comentario_id= 23;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 24;
update comentario set texto = 'Aliquam sit amet diam in magna bibendum imperdiet.'where comentario_id= 25;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 26;
update comentario set texto = 'Nam dui.'where comentario_id= 27;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 28;
update comentario set texto = 'Mauris lacinia sapien quis libero.'where comentario_id= 29;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 30;
update comentario set texto = 'Nulla tellus.'where comentario_id= 31;
update comentario set texto = 'Nam nulla.'where comentario_id= 32;
update comentario set texto = 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.'where comentario_id= 33;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 34;
update comentario set texto = 'Nulla tellus.'where comentario_id= 35;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 36;
update comentario set texto = 'Phasellus in felis.'where comentario_id= 37;
update comentario set texto = 'Integer a nibh.'where comentario_id= 38;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 39;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 40;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 41;
update comentario set texto = 'Curabitur convallis.'where comentario_id= 42;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 43;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 44;
update comentario set texto = 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'where comentario_id= 45;
update comentario set texto = 'Fusce posuere felis sed lacus.'where comentario_id= 46;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 47;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 48;
update comentario set texto = 'In congue.'where comentario_id= 49;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 50;
update comentario set texto = 'Curabitur at ipsum ac tellus semper interdum.'where comentario_id= 51;
update comentario set texto = 'Ut at dolor quis odio consequat varius.'where comentario_id= 52;
update comentario set texto = 'Donec quis orci eget orci vehicula condimentum.'where comentario_id= 53;
update comentario set texto = 'Phasellus in felis.'where comentario_id= 54;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 55;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 56;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 57;
update comentario set texto = 'Etiam justo.'where comentario_id= 58;
update comentario set texto = 'Morbi quis tortor id nulla ultrices aliquet.'where comentario_id= 59;
update comentario set texto = 'Nunc nisl.'where comentario_id= 60;
update comentario set texto = 'Donec vitae nisi.'where comentario_id= 61;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 62;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 63;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 64;
update comentario set texto = 'Maecenas rhoncus aliquam lacus.'where comentario_id= 65;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 66;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 67;
update comentario set texto = 'Sed ante.'where comentario_id= 68;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 69;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 70;
update comentario set texto = 'Curabitur in libero ut massa volutpat convallis.'where comentario_id= 71;
update comentario set texto = 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.'where comentario_id= 72;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.'where comentario_id= 73;
update comentario set texto = 'Integer non velit.'where comentario_id= 74;
update comentario set texto = 'Duis ac nibh.'where comentario_id= 75;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 76;
update comentario set texto = 'In eleifend quam a odio.'where comentario_id= 77;
update comentario set texto = 'Sed sagittis.'where comentario_id= 78;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 79;
update comentario set texto = 'In eleifend quam a odio.'where comentario_id= 80;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 81;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 82;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 83;
update comentario set texto = 'Duis aliquam convallis nunc.'where comentario_id= 84;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 85;
update comentario set texto = 'Integer a nibh.'where comentario_id= 86;
update comentario set texto = 'Curabitur at ipsum ac tellus semper interdum.'where comentario_id= 87;
update comentario set texto = 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.'where comentario_id= 88;
update comentario set texto = 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.'where comentario_id= 89;
update comentario set texto = 'Aenean auctor gravida sem.'where comentario_id= 90;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 91;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 92;
update comentario set texto = 'In quis justo.'where comentario_id= 93;
update comentario set texto = 'Mauris lacinia sapien quis libero.'where comentario_id= 94;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 95;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 96;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 97;
update comentario set texto = 'Nulla tellus.'where comentario_id= 98;
update comentario set texto = 'Nulla justo.'where comentario_id= 99;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 100;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 101;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 102;
update comentario set texto = 'Nunc nisl.'where comentario_id= 103;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 104;
update comentario set texto = 'Aenean lectus.'where comentario_id= 105;
update comentario set texto = 'Integer ac neque.'where comentario_id= 106;
update comentario set texto = 'Nullam varius.'where comentario_id= 107;
update comentario set texto = 'Duis consequat dui nec nisi volutpat eleifend.'where comentario_id= 108;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 109;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 110;
update comentario set texto = 'Proin risus.'where comentario_id= 111;
update comentario set texto = 'Nam dui.'where comentario_id= 112;
update comentario set texto = 'Nulla facilisi.'where comentario_id= 113;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 114;
update comentario set texto = 'Pellentesque eget nunc.'where comentario_id= 115;
update comentario set texto = 'Vestibulum sed magna at nunc commodo placerat.'where comentario_id= 116;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 117;
update comentario set texto = 'Aliquam sit amet diam in magna bibendum imperdiet.'where comentario_id= 118;
update comentario set texto = 'Duis bibendum.'where comentario_id= 119;
update comentario set texto = 'Nulla tellus.'where comentario_id= 120;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 121;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 122;
update comentario set texto = 'Nullam varius.'where comentario_id= 123;
update comentario set texto = 'Nunc nisl.'where comentario_id= 124;
update comentario set texto = 'Nam tristique tortor eu pede.'where comentario_id= 125;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 126;
update comentario set texto = 'Morbi quis tortor id nulla ultrices aliquet.'where comentario_id= 127;
update comentario set texto = 'Morbi quis tortor id nulla ultrices aliquet.'where comentario_id= 128;
update comentario set texto = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'where comentario_id= 129;
update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 130;
update comentario set texto = 'Donec dapibus.'where comentario_id= 131;
update comentario set texto = 'Sed sagittis.'where comentario_id= 132;
update comentario set texto = 'Nulla mollis molestie lorem.'where comentario_id= 133;
update comentario set texto = 'Aliquam quis turpis eget elit sodales scelerisque.'where comentario_id= 134;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 135;
update comentario set texto = 'Integer non velit.'where comentario_id= 136;
update comentario set texto = 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'where comentario_id= 137;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 138;
update comentario set texto = 'Nulla tellus.'where comentario_id= 139;
update comentario set texto = 'Praesent lectus.'where comentario_id= 140;
update comentario set texto = 'Aenean fermentum.'where comentario_id= 141;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 142;
update comentario set texto = 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'where comentario_id= 143;
update comentario set texto = 'Aliquam erat volutpat.'where comentario_id= 144;
update comentario set texto = 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'where comentario_id= 145;
update comentario set texto = 'Ut at dolor quis odio consequat varius.'where comentario_id= 146;
update comentario set texto = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'where comentario_id= 147;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 148;
update comentario set texto = 'Nullam sit amet turpis elementum ligula vehicula consequat.'where comentario_id= 149;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 150;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 151;
update comentario set texto = 'Pellentesque viverra pede ac diam.'where comentario_id= 152;
update comentario set texto = 'Integer non velit.'where comentario_id= 153;
update comentario set texto = 'Donec dapibus.'where comentario_id= 154;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 155;
update comentario set texto = 'Aliquam sit amet diam in magna bibendum imperdiet.'where comentario_id= 156;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 157;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 158;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 159;
update comentario set texto = 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'where comentario_id= 160;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 161;
update comentario set texto = 'Quisque ut erat.'where comentario_id= 162;
update comentario set texto = 'Maecenas ut massa quis augue luctus tincidunt.'where comentario_id= 163;
update comentario set texto = 'Nunc nisl.'where comentario_id= 164;
update comentario set texto = 'Curabitur in libero ut massa volutpat convallis.'where comentario_id= 165;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 166;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 167;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 168;
update comentario set texto = 'Maecenas tincidunt lacus at velit.'where comentario_id= 169;
update comentario set texto = 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.'where comentario_id= 170;
update comentario set texto = 'Donec ut dolor.'where comentario_id= 171;
update comentario set texto = 'Nam tristique tortor eu pede.'where comentario_id= 172;
update comentario set texto = 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.'where comentario_id= 173;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 174;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 175;
update comentario set texto = 'Morbi a ipsum.'where comentario_id= 176;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 177;
update comentario set texto = 'Curabitur convallis.'where comentario_id= 178;
update comentario set texto = 'Nullam varius.'where comentario_id= 179;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 180;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 181;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 182;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 183;
update comentario set texto = 'Donec vitae nisi.'where comentario_id= 184;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 185;
update comentario set texto = 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'where comentario_id= 186;
update comentario set texto = 'Mauris sit amet eros.'where comentario_id= 187;
update comentario set texto = 'Aliquam erat volutpat.'where comentario_id= 188;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 189;
update comentario set texto = 'In congue.'where comentario_id= 190;
update comentario set texto = 'Nunc purus.'where comentario_id= 191;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 192;
update comentario set texto = 'Aenean auctor gravida sem.'where comentario_id= 193;
update comentario set texto = 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'where comentario_id= 194;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 195;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 196;
update comentario set texto = 'Pellentesque at nulla.'where comentario_id= 197;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 198;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 199;
update comentario set texto = 'Duis aliquam convallis nunc.'where comentario_id= 200;
update comentario set texto = 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'where comentario_id= 201;
update comentario set texto = 'Vivamus tortor.'where comentario_id= 202;
update comentario set texto = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'where comentario_id= 203;
update comentario set texto = 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'where comentario_id= 204;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 205;
update comentario set texto = 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.'where comentario_id= 206;
update comentario set texto = 'Nunc rhoncus dui vel sem.'where comentario_id= 207;
update comentario set texto = 'Aliquam quis turpis eget elit sodales scelerisque.'where comentario_id= 208;
update comentario set texto = 'Donec posuere metus vitae ipsum.'where comentario_id= 209;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 210;
update comentario set texto = 'In quis justo.'where comentario_id= 211;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 212;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 213;
update comentario set texto = 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.'where comentario_id= 214;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 215;
update comentario set texto = 'Vivamus in felis eu sapien cursus vestibulum.'where comentario_id= 216;
update comentario set texto = 'Vivamus in felis eu sapien cursus vestibulum.'where comentario_id= 217;
update comentario set texto = 'Praesent lectus.'where comentario_id= 218;
update comentario set texto = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'where comentario_id= 219;
update comentario set texto = 'Praesent lectus.'where comentario_id= 220;
update comentario set texto = 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.'where comentario_id= 221;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 222;
update comentario set texto = 'Nunc rhoncus dui vel sem.'where comentario_id= 223;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 224;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 225;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 226;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 227;
update comentario set texto = 'Etiam vel augue.'where comentario_id= 228;
update comentario set texto = 'Nulla nisl.'where comentario_id= 229;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 230;
update comentario set texto = 'Proin eu mi.'where comentario_id= 231;
update comentario set texto = 'Praesent blandit.'where comentario_id= 232;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 233;
update comentario set texto = 'Nam dui.'where comentario_id= 234;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 235;
update comentario set texto = 'Nunc rhoncus dui vel sem.'where comentario_id= 236;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 237;
update comentario set texto = 'Proin risus.'where comentario_id= 238;
update comentario set texto = 'Duis bibendum.'where comentario_id= 239;
update comentario set texto = 'Vivamus vel nulla eget eros elementum pellentesque.'where comentario_id= 240;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 241;
update comentario set texto = 'Pellentesque eget nunc.'where comentario_id= 242;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 243;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 244;
update comentario set texto = 'Sed vel enim sit amet nunc viverra dapibus.'where comentario_id= 245;
update comentario set texto = 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'where comentario_id= 246;
update comentario set texto = 'Maecenas rhoncus aliquam lacus.'where comentario_id= 247;
update comentario set texto = 'Donec dapibus.'where comentario_id= 248;
update comentario set texto = 'Duis mattis egestas metus.'where comentario_id= 249;
update comentario set texto = 'Donec ut dolor.'where comentario_id= 250;
update comentario set texto = 'Maecenas ut massa quis augue luctus tincidunt.'where comentario_id= 251;
update comentario set texto = 'Phasellus id sapien in sapien iaculis congue.'where comentario_id= 252;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 253;
update comentario set texto = 'Donec posuere metus vitae ipsum.'where comentario_id= 254;
update comentario set texto = 'Nulla ac enim.'where comentario_id= 255;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 256;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 257;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 258;
update comentario set texto = 'Proin at turpis a pede posuere nonummy.'where comentario_id= 259;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 260;
update comentario set texto = 'Mauris lacinia sapien quis libero.'where comentario_id= 261;
update comentario set texto = 'Quisque ut erat.'where comentario_id= 262;
update comentario set texto = 'Proin eu mi.'where comentario_id= 263;
update comentario set texto = 'Pellentesque viverra pede ac diam.'where comentario_id= 264;
update comentario set texto = 'Nam tristique tortor eu pede.'where comentario_id= 265;
update comentario set texto = 'Nam tristique tortor eu pede.'where comentario_id= 266;
update comentario set texto = 'Mauris sit amet eros.'where comentario_id= 267;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.'where comentario_id= 268;
update comentario set texto = 'Nulla ac enim.'where comentario_id= 269;
update comentario set texto = 'Donec posuere metus vitae ipsum.'where comentario_id= 270;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 271;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 272;
update comentario set texto = 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'where comentario_id= 273;
update comentario set texto = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'where comentario_id= 274;
update comentario set texto = 'Integer non velit.'where comentario_id= 275;
update comentario set texto = 'Mauris sit amet eros.'where comentario_id= 276;
update comentario set texto = 'Maecenas rhoncus aliquam lacus.'where comentario_id= 277;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 278;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 279;
update comentario set texto = 'Aliquam erat volutpat.'where comentario_id= 280;
update comentario set texto = 'Duis bibendum.'where comentario_id= 281;
update comentario set texto = 'Suspendisse accumsan tortor quis turpis.'where comentario_id= 282;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 283;
update comentario set texto = 'Vivamus tortor.'where comentario_id= 284;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 285;
update comentario set texto = 'Aliquam quis turpis eget elit sodales scelerisque.'where comentario_id= 286;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 287;
update comentario set texto = 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.'where comentario_id= 288;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 289;
update comentario set texto = 'Aenean lectus.'where comentario_id= 290;
update comentario set texto = 'Etiam pretium iaculis justo.'where comentario_id= 291;
update comentario set texto = 'Duis ac nibh.'where comentario_id= 292;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 293;
update comentario set texto = 'Suspendisse accumsan tortor quis turpis.'where comentario_id= 294;
update comentario set texto = 'Maecenas pulvinar lobortis est.'where comentario_id= 295;
update comentario set texto = 'Vivamus vestibulum sagittis sapien.'where comentario_id= 296;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 297;
update comentario set texto = 'In congue.'where comentario_id= 298;
update comentario set texto = 'Sed vel enim sit amet nunc viverra dapibus.'where comentario_id= 299;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 300;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 301;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 302;
update comentario set texto = 'Phasellus sit amet erat.'where comentario_id= 303;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 304;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 305;
update comentario set texto = 'Donec semper sapien a libero.'where comentario_id= 306;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 307;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 308;
update comentario set texto = 'Etiam vel augue.'where comentario_id= 309;
update comentario set texto = 'Morbi porttitor lorem id ligula.'where comentario_id= 310;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 311;
update comentario set texto = 'Nulla suscipit ligula in lacus.'where comentario_id= 312;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 313;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 314;
update comentario set texto = 'Proin risus.'where comentario_id= 315;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 316;
update comentario set texto = 'Maecenas tincidunt lacus at velit.'where comentario_id= 317;
update comentario set texto = 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'where comentario_id= 318;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 319;
update comentario set texto = 'Nulla ut erat id mauris vulputate elementum.'where comentario_id= 320;
update comentario set texto = 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'where comentario_id= 321;
update comentario set texto = 'Morbi a ipsum.'where comentario_id= 322;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 323;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 324;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 325;
update comentario set texto = 'In congue.'where comentario_id= 326;
update comentario set texto = 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'where comentario_id= 327;
update comentario set texto = 'Vestibulum sed magna at nunc commodo placerat.'where comentario_id= 328;
update comentario set texto = 'Quisque ut erat.'where comentario_id= 329;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 330;
update comentario set texto = 'Nulla facilisi.'where comentario_id= 331;
update comentario set texto = 'Donec dapibus.'where comentario_id= 332;
update comentario set texto = 'Nulla justo.'where comentario_id= 333;
update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 334;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 335;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 336;
update comentario set texto = 'Ut tellus.'where comentario_id= 337;
update comentario set texto = 'Duis aliquam convallis nunc.'where comentario_id= 338;
update comentario set texto = 'Nam tristique tortor eu pede.'where comentario_id= 339;
update comentario set texto = 'Aliquam erat volutpat.'where comentario_id= 340;
update comentario set texto = 'Nulla tellus.'where comentario_id= 341;
update comentario set texto = 'Curabitur convallis.'where comentario_id= 342;
update comentario set texto = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'where comentario_id= 343;
update comentario set texto = 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'where comentario_id= 344;
update comentario set texto = 'Nullam varius.'where comentario_id= 345;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 346;
update comentario set texto = 'Curabitur convallis.'where comentario_id= 347;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 348;
update comentario set texto = 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'where comentario_id= 349;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.'where comentario_id= 350;
update comentario set texto = 'Integer a nibh.'where comentario_id= 351;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 352;
update comentario set texto = 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'where comentario_id= 353;
update comentario set texto = 'Curabitur in libero ut massa volutpat convallis.'where comentario_id= 354;
update comentario set texto = 'Donec vitae nisi.'where comentario_id= 355;
update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 356;
update comentario set texto = 'Vivamus in felis eu sapien cursus vestibulum.'where comentario_id= 357;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 358;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.'where comentario_id= 359;
update comentario set texto = 'Nulla justo.'where comentario_id= 360;
update comentario set texto = 'Pellentesque eget nunc.'where comentario_id= 361;
update comentario set texto = 'Nulla facilisi.'where comentario_id= 362;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 363;
update comentario set texto = 'Aenean lectus.'where comentario_id= 364;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 365;
update comentario set texto = 'Nulla ut erat id mauris vulputate elementum.'where comentario_id= 366;
update comentario set texto = 'Ut at dolor quis odio consequat varius.'where comentario_id= 367;
update comentario set texto = 'Aliquam erat volutpat.'where comentario_id= 368;
update comentario set texto = 'In congue.'where comentario_id= 369;
update comentario set texto = 'Mauris sit amet eros.'where comentario_id= 370;
update comentario set texto = 'Nulla nisl.'where comentario_id= 371;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 372;
update comentario set texto = 'Curabitur at ipsum ac tellus semper interdum.'where comentario_id= 373;
update comentario set texto = 'Praesent blandit lacinia erat.'where comentario_id= 374;
update comentario set texto = 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.'where comentario_id= 375;
update comentario set texto = 'Pellentesque at nulla.'where comentario_id= 376;
update comentario set texto = 'Proin interdum mauris non ligula pellentesque ultrices.'where comentario_id= 377;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 378;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 379;
update comentario set texto = 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.'where comentario_id= 380;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 381;
update comentario set texto = 'In eleifend quam a odio.'where comentario_id= 382;
update comentario set texto = 'Maecenas tincidunt lacus at velit.'where comentario_id= 383;
update comentario set texto = 'Nullam varius.'where comentario_id= 384;
update comentario set texto = 'Cras pellentesque volutpat dui.'where comentario_id= 385;
update comentario set texto = 'Duis bibendum.'where comentario_id= 386;
update comentario set texto = 'Nulla mollis molestie lorem.'where comentario_id= 387;
update comentario set texto = 'In congue.'where comentario_id= 388;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 389;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 390;
update comentario set texto = 'Curabitur in libero ut massa volutpat convallis.'where comentario_id= 391;
update comentario set texto = 'Aenean sit amet justo.'where comentario_id= 392;
update comentario set texto = 'Proin at turpis a pede posuere nonummy.'where comentario_id= 393;
update comentario set texto = 'Nulla mollis molestie lorem.'where comentario_id= 394;
update comentario set texto = 'Proin at turpis a pede posuere nonummy.'where comentario_id= 395;
update comentario set texto = 'Maecenas ut massa quis augue luctus tincidunt.'where comentario_id= 396;
update comentario set texto = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'where comentario_id= 397;
update comentario set texto = 'In congue.'where comentario_id= 398;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.'where comentario_id= 399;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 400;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 401;
update comentario set texto = 'Vivamus vel nulla eget eros elementum pellentesque.'where comentario_id= 402;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 403;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 404;
update comentario set texto = 'Sed sagittis.'where comentario_id= 405;
update comentario set texto = 'Mauris sit amet eros.'where comentario_id= 406;
update comentario set texto = 'Ut tellus.'where comentario_id= 407;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 408;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 409;
update comentario set texto = 'Proin at turpis a pede posuere nonummy.'where comentario_id= 410;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 411;
update comentario set texto = 'Nulla tempus.'where comentario_id= 412;
update comentario set texto = 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'where comentario_id= 413;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 414;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 415;
update comentario set texto = 'Donec quis orci eget orci vehicula condimentum.'where comentario_id= 416;
update comentario set texto = 'Morbi non lectus.'where comentario_id= 417;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 418;
update comentario set texto = 'In sagittis dui vel nisl.'where comentario_id= 419;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 420;
update comentario set texto = 'Maecenas ut massa quis augue luctus tincidunt.'where comentario_id= 421;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 422;
update comentario set texto = 'Donec quis orci eget orci vehicula condimentum.'where comentario_id= 423;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 424;
update comentario set texto = 'Nulla suscipit ligula in lacus.'where comentario_id= 425;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 426;
update comentario set texto = 'Integer ac leo.'where comentario_id= 427;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 428;
update comentario set texto = 'Vestibulum sed magna at nunc commodo placerat.'where comentario_id= 429;
update comentario set texto = 'In congue.'where comentario_id= 430;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 431;
update comentario set texto = 'Duis bibendum.'where comentario_id= 432;
update comentario set texto = 'Integer non velit.'where comentario_id= 433;
update comentario set texto = 'Nunc nisl.'where comentario_id= 434;
update comentario set texto = 'Aenean sit amet justo.'where comentario_id= 435;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 436;
update comentario set texto = 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.'where comentario_id= 437;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 438;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 439;
update comentario set texto = 'Nullam sit amet turpis elementum ligula vehicula consequat.'where comentario_id= 440;
update comentario set texto = 'Donec semper sapien a libero.'where comentario_id= 441;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 442;
update comentario set texto = 'Proin interdum mauris non ligula pellentesque ultrices.'where comentario_id= 443;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 444;
update comentario set texto = 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'where comentario_id= 445;
update comentario set texto = 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'where comentario_id= 446;
update comentario set texto = 'Donec ut mauris eget massa tempor convallis.'where comentario_id= 447;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 448;
update comentario set texto = 'Fusce posuere felis sed lacus.'where comentario_id= 449;
update comentario set texto = 'Nulla ut erat id mauris vulputate elementum.'where comentario_id= 450;
update comentario set texto = 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'where comentario_id= 451;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 452;
update comentario set texto = 'Nulla ac enim.'where comentario_id= 453;
update comentario set texto = 'Aliquam non mauris.'where comentario_id= 454;
update comentario set texto = 'Ut tellus.'where comentario_id= 455;
update comentario set texto = 'Quisque ut erat.'where comentario_id= 456;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 457;
update comentario set texto = 'Pellentesque at nulla.'where comentario_id= 458;
update comentario set texto = 'Morbi a ipsum.'where comentario_id= 459;
update comentario set texto = 'Nulla tempus.'where comentario_id= 460;
update comentario set texto = 'Duis bibendum.'where comentario_id= 461;
update comentario set texto = 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'where comentario_id= 462;
update comentario set texto = 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.'where comentario_id= 463;
update comentario set texto = 'Praesent lectus.'where comentario_id= 464;
update comentario set texto = 'Maecenas pulvinar lobortis est.'where comentario_id= 465;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 466;
update comentario set texto = 'Cras pellentesque volutpat dui.'where comentario_id= 467;
update comentario set texto = 'Ut at dolor quis odio consequat varius.'where comentario_id= 468;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 469;
update comentario set texto = 'Curabitur convallis.'where comentario_id= 470;
update comentario set texto = 'In eleifend quam a odio.'where comentario_id= 471;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 472;
update comentario set texto = 'Etiam pretium iaculis justo.'where comentario_id= 473;
update comentario set texto = 'Nulla tempus.'where comentario_id= 474;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 475;
update comentario set texto = 'Vivamus vestibulum sagittis sapien.'where comentario_id= 476;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.'where comentario_id= 477;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.'where comentario_id= 478;
update comentario set texto = 'Aenean fermentum.'where comentario_id= 479;
update comentario set texto = 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'where comentario_id= 480;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 481;
update comentario set texto = 'Proin eu mi.'where comentario_id= 482;
update comentario set texto = 'Nam nulla.'where comentario_id= 483;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 484;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 485;
update comentario set texto = 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'where comentario_id= 486;
update comentario set texto = 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'where comentario_id= 487;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 488;
update comentario set texto = 'Curabitur at ipsum ac tellus semper interdum.'where comentario_id= 489;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.'where comentario_id= 490;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 491;
update comentario set texto = 'Quisque ut erat.'where comentario_id= 492;
update comentario set texto = 'Nulla tempus.'where comentario_id= 493;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 494;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 495;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 496;
update comentario set texto = 'Nunc rhoncus dui vel sem.'where comentario_id= 497;
update comentario set texto = 'Vivamus in felis eu sapien cursus vestibulum.'where comentario_id= 498;
update comentario set texto = 'Nulla ut erat id mauris vulputate elementum.'where comentario_id= 499;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 500;
update comentario set texto = 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'where comentario_id= 501;
update comentario set texto = 'Vivamus vel nulla eget eros elementum pellentesque.'where comentario_id= 502;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 503;
update comentario set texto = 'Donec ut dolor.'where comentario_id= 504;
update comentario set texto = 'Curabitur convallis.'where comentario_id= 505;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 506;
update comentario set texto = 'Nulla mollis molestie lorem.'where comentario_id= 507;
update comentario set texto = 'In congue.'where comentario_id= 508;
update comentario set texto = 'Integer a nibh.'where comentario_id= 509;
update comentario set texto = 'Vestibulum sed magna at nunc commodo placerat.'where comentario_id= 510;
update comentario set texto = 'Nulla tellus.'where comentario_id= 511;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 512;
update comentario set texto = 'Donec semper sapien a libero.'where comentario_id= 513;
update comentario set texto = 'Maecenas rhoncus aliquam lacus.'where comentario_id= 514;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 515;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 516;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 517;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 518;
update comentario set texto = 'Morbi non lectus.'where comentario_id= 519;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 520;
update comentario set texto = 'Integer ac leo.'where comentario_id= 521;
update comentario set texto = 'Duis mattis egestas metus.'where comentario_id= 522;
update comentario set texto = 'Duis bibendum.'where comentario_id= 523;
update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 524;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 525;
update comentario set texto = 'Aenean lectus.'where comentario_id= 526;
update comentario set texto = 'Sed sagittis.'where comentario_id= 527;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 528;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 529;
update comentario set texto = 'Integer ac leo.'where comentario_id= 530;
update comentario set texto = 'Cras pellentesque volutpat dui.'where comentario_id= 531;
update comentario set texto = 'In congue.'where comentario_id= 532;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 533;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 534;
update comentario set texto = 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'where comentario_id= 535;
update comentario set texto = 'Quisque ut erat.'where comentario_id= 536;
update comentario set texto = 'Suspendisse accumsan tortor quis turpis.'where comentario_id= 537;
update comentario set texto = 'Mauris lacinia sapien quis libero.'where comentario_id= 538;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 539;
update comentario set texto = 'Praesent blandit lacinia erat.'where comentario_id= 540;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 541;
update comentario set texto = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'where comentario_id= 542;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 543;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 544;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 545;
update comentario set texto = 'Nam nulla.'where comentario_id= 546;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 547;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 548;
update comentario set texto = 'Praesent blandit.'where comentario_id= 549;
update comentario set texto = 'In eleifend quam a odio.'where comentario_id= 550;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 551;
update comentario set texto = 'Morbi porttitor lorem id ligula.'where comentario_id= 552;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 553;
update comentario set texto = 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.'where comentario_id= 554;
update comentario set texto = 'Curabitur in libero ut massa volutpat convallis.'where comentario_id= 555;
update comentario set texto = 'Etiam vel augue.'where comentario_id= 556;
update comentario set texto = 'Duis ac nibh.'where comentario_id= 557;
update comentario set texto = 'Donec ut dolor.'where comentario_id= 558;
update comentario set texto = 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'where comentario_id= 559;
update comentario set texto = 'Suspendisse accumsan tortor quis turpis.'where comentario_id= 560;
update comentario set texto = 'Nam nulla.'where comentario_id= 561;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 562;
update comentario set texto = 'Aliquam sit amet diam in magna bibendum imperdiet.'where comentario_id= 563;
update comentario set texto = 'Morbi a ipsum.'where comentario_id= 564;
update comentario set texto = 'Vivamus tortor.'where comentario_id= 565;
update comentario set texto = 'Nam dui.'where comentario_id= 566;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 567;
update comentario set texto = 'Quisque ut erat.'where comentario_id= 568;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 569;
update comentario set texto = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'where comentario_id= 570;
update comentario set texto = 'In quis justo.'where comentario_id= 571;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 572;
update comentario set texto = 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'where comentario_id= 573;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.'where comentario_id= 574;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 575;
update comentario set texto = 'Vivamus vestibulum sagittis sapien.'where comentario_id= 576;
update comentario set texto = 'Pellentesque at nulla.'where comentario_id= 577;
update comentario set texto = 'Nullam sit amet turpis elementum ligula vehicula consequat.'where comentario_id= 578;
update comentario set texto = 'Vestibulum sed magna at nunc commodo placerat.'where comentario_id= 579;
update comentario set texto = 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'where comentario_id= 580;
update comentario set texto = 'Integer ac neque.'where comentario_id= 581;
update comentario set texto = 'Nulla suscipit ligula in lacus.'where comentario_id= 582;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 583;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 584;
update comentario set texto = 'Cras pellentesque volutpat dui.'where comentario_id= 585;
update comentario set texto = 'Nulla ut erat id mauris vulputate elementum.'where comentario_id= 586;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 587;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 588;
update comentario set texto = 'Nulla nisl.'where comentario_id= 589;
update comentario set texto = 'Morbi quis tortor id nulla ultrices aliquet.'where comentario_id= 590;
update comentario set texto = 'Integer non velit.'where comentario_id= 591;
update comentario set texto = 'Etiam pretium iaculis justo.'where comentario_id= 592;
update comentario set texto = 'Fusce consequat.'where comentario_id= 593;
update comentario set texto = 'Suspendisse accumsan tortor quis turpis.'where comentario_id= 594;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 595;
update comentario set texto = 'In quis justo.'where comentario_id= 596;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 597;
update comentario set texto = 'Etiam justo.'where comentario_id= 598;
update comentario set texto = 'Sed sagittis.'where comentario_id= 599;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 600;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 601;
update comentario set texto = 'Proin interdum mauris non ligula pellentesque ultrices.'where comentario_id= 602;
update comentario set texto = 'Donec semper sapien a libero.'where comentario_id= 603;
update comentario set texto = 'In quis justo.'where comentario_id= 604;
update comentario set texto = 'In congue.'where comentario_id= 605;
update comentario set texto = 'Donec dapibus.'where comentario_id= 606;
update comentario set texto = 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'where comentario_id= 607;
update comentario set texto = 'Maecenas tincidunt lacus at velit.'where comentario_id= 608;
update comentario set texto = 'Nam nulla.'where comentario_id= 609;
update comentario set texto = 'Aenean fermentum.'where comentario_id= 610;
update comentario set texto = 'Aenean sit amet justo.'where comentario_id= 611;
update comentario set texto = 'Proin eu mi.'where comentario_id= 612;
update comentario set texto = 'Sed sagittis.'where comentario_id= 613;
update comentario set texto = 'Curabitur at ipsum ac tellus semper interdum.'where comentario_id= 614;
update comentario set texto = 'Cras non velit nec nisi vulputate nonummy.'where comentario_id= 615;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 616;
update comentario set texto = 'Praesent blandit.'where comentario_id= 617;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 618;
update comentario set texto = 'Nulla tellus.'where comentario_id= 619;
update comentario set texto = 'Nulla tempus.'where comentario_id= 620;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 621;
update comentario set texto = 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.'where comentario_id= 622;
update comentario set texto = 'Donec quis orci eget orci vehicula condimentum.'where comentario_id= 623;
update comentario set texto = 'Nulla tempus.'where comentario_id= 624;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 625;
update comentario set texto = 'Nulla ac enim.'where comentario_id= 626;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 627;
update comentario set texto = 'Aenean lectus.'where comentario_id= 628;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 629;
update comentario set texto = 'Morbi ut odio.'where comentario_id= 630;
update comentario set texto = 'Donec ut mauris eget massa tempor convallis.'where comentario_id= 631;
update comentario set texto = 'Duis aliquam convallis nunc.'where comentario_id= 632;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 633;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 634;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 635;
update comentario set texto = 'Phasellus in felis.'where comentario_id= 636;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 637;
update comentario set texto = 'Praesent blandit.'where comentario_id= 638;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 639;
update comentario set texto = 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'where comentario_id= 640;
update comentario set texto = 'Mauris sit amet eros.'where comentario_id= 641;
update comentario set texto = 'Vivamus vel nulla eget eros elementum pellentesque.'where comentario_id= 642;
update comentario set texto = 'Nunc purus.'where comentario_id= 643;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 644;
update comentario set texto = 'Nulla justo.'where comentario_id= 645;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 646;
update comentario set texto = 'Morbi quis tortor id nulla ultrices aliquet.'where comentario_id= 647;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 648;
update comentario set texto = 'Nulla tempus.'where comentario_id= 649;
update comentario set texto = 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'where comentario_id= 650;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 651;
update comentario set texto = 'Nulla nisl.'where comentario_id= 652;
update comentario set texto = 'Morbi porttitor lorem id ligula.'where comentario_id= 653;
update comentario set texto = 'Vivamus tortor.'where comentario_id= 654;
update comentario set texto = 'Pellentesque viverra pede ac diam.'where comentario_id= 655;
update comentario set texto = 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'where comentario_id= 656;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 657;
update comentario set texto = 'Sed vel enim sit amet nunc viverra dapibus.'where comentario_id= 658;
update comentario set texto = 'Nulla tellus.'where comentario_id= 659;
update comentario set texto = 'Nulla suscipit ligula in lacus.'where comentario_id= 660;
update comentario set texto = 'Etiam vel augue.'where comentario_id= 661;
update comentario set texto = 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.'where comentario_id= 662;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 663;
update comentario set texto = 'Maecenas tincidunt lacus at velit.'where comentario_id= 664;
update comentario set texto = 'Morbi a ipsum.'where comentario_id= 665;
update comentario set texto = 'Nam nulla.'where comentario_id= 666;
update comentario set texto = 'Cras pellentesque volutpat dui.'where comentario_id= 667;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 668;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 669;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 670;
update comentario set texto = 'Praesent blandit lacinia erat.'where comentario_id= 671;
update comentario set texto = 'Aliquam non mauris.'where comentario_id= 672;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 673;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 674;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 675;
update comentario set texto = 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'where comentario_id= 676;
update comentario set texto = 'Donec posuere metus vitae ipsum.'where comentario_id= 677;
update comentario set texto = 'Ut at dolor quis odio consequat varius.'where comentario_id= 678;
update comentario set texto = 'Integer a nibh.'where comentario_id= 679;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 680;
update comentario set texto = 'Vestibulum sed magna at nunc commodo placerat.'where comentario_id= 681;
update comentario set texto = 'Phasellus id sapien in sapien iaculis congue.'where comentario_id= 682;
update comentario set texto = 'Vestibulum sed magna at nunc commodo placerat.'where comentario_id= 683;
update comentario set texto = 'Nulla tempus.'where comentario_id= 684;
update comentario set texto = 'Vivamus vestibulum sagittis sapien.'where comentario_id= 685;
update comentario set texto = 'Nunc nisl.'where comentario_id= 686;
update comentario set texto = 'Nulla nisl.'where comentario_id= 687;
update comentario set texto = 'Proin eu mi.'where comentario_id= 688;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 689;
update comentario set texto = 'Proin interdum mauris non ligula pellentesque ultrices.'where comentario_id= 690;
update comentario set texto = 'Nulla suscipit ligula in lacus.'where comentario_id= 691;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 692;
update comentario set texto = 'In quis justo.'where comentario_id= 693;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 694;
update comentario set texto = 'Integer a nibh.'where comentario_id= 695;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 696;
update comentario set texto = 'Nulla tempus.'where comentario_id= 697;
update comentario set texto = 'Vivamus vel nulla eget eros elementum pellentesque.'where comentario_id= 698;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 699;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 700;
update comentario set texto = 'Maecenas pulvinar lobortis est.'where comentario_id= 701;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 702;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 703;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 704;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 705;
update comentario set texto = 'Aenean auctor gravida sem.'where comentario_id= 706;
update comentario set texto = 'Donec semper sapien a libero.'where comentario_id= 707;
update comentario set texto = 'Sed sagittis.'where comentario_id= 708;
update comentario set texto = 'Duis bibendum.'where comentario_id= 709;
update comentario set texto = 'Maecenas pulvinar lobortis est.'where comentario_id= 710;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 711;
update comentario set texto = 'Duis ac nibh.'where comentario_id= 712;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 713;
update comentario set texto = 'Donec ut mauris eget massa tempor convallis.'where comentario_id= 714;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 715;
update comentario set texto = 'Nullam sit amet turpis elementum ligula vehicula consequat.'where comentario_id= 716;
update comentario set texto = 'In quis justo.'where comentario_id= 717;
update comentario set texto = 'In sagittis dui vel nisl.'where comentario_id= 718;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 719;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 720;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 721;
update comentario set texto = 'Aliquam erat volutpat.'where comentario_id= 722;
update comentario set texto = 'Nam nulla.'where comentario_id= 723;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 724;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 725;
update comentario set texto = 'Curabitur convallis.'where comentario_id= 726;
update comentario set texto = 'Donec vitae nisi.'where comentario_id= 727;
update comentario set texto = 'Nulla mollis molestie lorem.'where comentario_id= 728;
update comentario set texto = 'Aenean sit amet justo.'where comentario_id= 729;
update comentario set texto = 'In quis justo.'where comentario_id= 730;
update comentario set texto = 'Nunc purus.'where comentario_id= 731;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 732;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 733;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 734;
update comentario set texto = 'Integer non velit.'where comentario_id= 735;
update comentario set texto = 'Nulla tempus.'where comentario_id= 736;
update comentario set texto = 'Duis at velit eu est congue elementum.'where comentario_id= 737;
update comentario set texto = 'In congue.'where comentario_id= 738;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 739;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 740;
update comentario set texto = 'In eleifend quam a odio.'where comentario_id= 741;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 742;
update comentario set texto = 'Proin at turpis a pede posuere nonummy.'where comentario_id= 743;
update comentario set texto = 'Phasellus id sapien in sapien iaculis congue.'where comentario_id= 744;
update comentario set texto = 'Proin interdum mauris non ligula pellentesque ultrices.'where comentario_id= 745;
update comentario set texto = 'Vivamus in felis eu sapien cursus vestibulum.'where comentario_id= 746;
update comentario set texto = 'Nullam sit amet turpis elementum ligula vehicula consequat.'where comentario_id= 747;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 748;
update comentario set texto = 'Donec posuere metus vitae ipsum.'where comentario_id= 749;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 750;
update comentario set texto = 'Pellentesque at nulla.'where comentario_id= 751;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 752;
update comentario set texto = 'Cras non velit nec nisi vulputate nonummy.'where comentario_id= 753;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 754;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 755;
update comentario set texto = 'Proin interdum mauris non ligula pellentesque ultrices.'where comentario_id= 756;
update comentario set texto = 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'where comentario_id= 757;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 758;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 759;
update comentario set texto = 'Nunc purus.'where comentario_id= 760;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 761;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 762;
update comentario set texto = 'Cras non velit nec nisi vulputate nonummy.'where comentario_id= 763;
update comentario set texto = 'Nullam varius.'where comentario_id= 764;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 765;
update comentario set texto = 'Sed ante.'where comentario_id= 766;
update comentario set texto = 'Nulla facilisi.'where comentario_id= 767;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 768;
update comentario set texto = 'Phasellus id sapien in sapien iaculis congue.'where comentario_id= 769;
update comentario set texto = 'Proin eu mi.'where comentario_id= 770;
update comentario set texto = 'Morbi ut odio.'where comentario_id= 771;
update comentario set texto = 'Nulla tellus.'where comentario_id= 772;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 773;
update comentario set texto = 'Donec vitae nisi.'where comentario_id= 774;
update comentario set texto = 'In blandit ultrices enim.'where comentario_id= 775;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 776;
update comentario set texto = 'Suspendisse ornare consequat lectus.'where comentario_id= 777;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 778;
update comentario set texto = 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.'where comentario_id= 779;
update comentario set texto = 'Praesent lectus.'where comentario_id= 780;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'where comentario_id= 781;
update comentario set texto = 'Donec posuere metus vitae ipsum.'where comentario_id= 782;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 783;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 784;
update comentario set texto = 'Nulla mollis molestie lorem.'where comentario_id= 785;
update comentario set texto = 'Nulla justo.'where comentario_id= 786;
update comentario set texto = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'where comentario_id= 787;
update comentario set texto = 'Vivamus vestibulum sagittis sapien.'where comentario_id= 788;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 789;
update comentario set texto = 'Fusce posuere felis sed lacus.'where comentario_id= 790;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 791;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 792;
update comentario set texto = 'Nunc purus.'where comentario_id= 793;
update comentario set texto = 'Donec ut dolor.'where comentario_id= 794;
update comentario set texto = 'Phasellus sit amet erat.'where comentario_id= 795;
update comentario set texto = 'Aliquam quis turpis eget elit sodales scelerisque.'where comentario_id= 796;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 797;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 798;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 799;
update comentario set texto = 'Curabitur in libero ut massa volutpat convallis.'where comentario_id= 800;
update comentario set texto = 'Duis aliquam convallis nunc.'where comentario_id= 801;
update comentario set texto = 'Phasellus sit amet erat.'where comentario_id= 802;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 803;
update comentario set texto = 'Mauris lacinia sapien quis libero.'where comentario_id= 804;
update comentario set texto = 'Duis bibendum.'where comentario_id= 805;
update comentario set texto = 'Maecenas tincidunt lacus at velit.'where comentario_id= 806;
update comentario set texto = 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'where comentario_id= 807;
update comentario set texto = 'Nunc rhoncus dui vel sem.'where comentario_id= 808;
update comentario set texto = 'Nulla facilisi.'where comentario_id= 809;
update comentario set texto = 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'where comentario_id= 810;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 811;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 812;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 813;
update comentario set texto = 'Aliquam sit amet diam in magna bibendum imperdiet.'where comentario_id= 814;
update comentario set texto = 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'where comentario_id= 815;
update comentario set texto = 'Morbi porttitor lorem id ligula.'where comentario_id= 816;
update comentario set texto = 'Aliquam non mauris.'where comentario_id= 817;
update comentario set texto = 'Curabitur at ipsum ac tellus semper interdum.'where comentario_id= 818;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 819;
update comentario set texto = 'Donec quis orci eget orci vehicula condimentum.'where comentario_id= 820;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 821;
update comentario set texto = 'Aliquam non mauris.'where comentario_id= 822;
update comentario set texto = 'Curabitur gravida nisi at nibh.'where comentario_id= 823;
update comentario set texto = 'Etiam vel augue.'where comentario_id= 824;
update comentario set texto = 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'where comentario_id= 825;
update comentario set texto = 'Nam nulla.'where comentario_id= 826;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 827;
update comentario set texto = 'Donec dapibus.'where comentario_id= 828;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 829;
update comentario set texto = 'Donec ut mauris eget massa tempor convallis.'where comentario_id= 830;
update comentario set texto = 'Curabitur at ipsum ac tellus semper interdum.'where comentario_id= 831;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 832;
update comentario set texto = 'Sed sagittis.'where comentario_id= 833;
update comentario set texto = 'Nulla ut erat id mauris vulputate elementum.'where comentario_id= 834;
update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 835;
update comentario set texto = 'Proin at turpis a pede posuere nonummy.'where comentario_id= 836;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 837;
update comentario set texto = 'Cras pellentesque volutpat dui.'where comentario_id= 838;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 839;
update comentario set texto = 'Maecenas ut massa quis augue luctus tincidunt.'where comentario_id= 840;
update comentario set texto = 'Nulla facilisi.'where comentario_id= 841;
update comentario set texto = 'Etiam pretium iaculis justo.'where comentario_id= 842;
update comentario set texto = 'Nullam varius.'where comentario_id= 843;
update comentario set texto = 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'where comentario_id= 844;
update comentario set texto = 'Aenean fermentum.'where comentario_id= 845;
update comentario set texto = 'Nam dui.'where comentario_id= 846;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 847;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.'where comentario_id= 848;
update comentario set texto = 'Donec ut mauris eget massa tempor convallis.'where comentario_id= 849;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 850;
update comentario set texto = 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.'where comentario_id= 851;
update comentario set texto = 'Aenean lectus.'where comentario_id= 852;
update comentario set texto = 'Proin eu mi.'where comentario_id= 853;
update comentario set texto = 'Nunc purus.'where comentario_id= 854;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 855;
update comentario set texto = 'Phasellus id sapien in sapien iaculis congue.'where comentario_id= 856;
update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 857;
update comentario set texto = 'Nulla suscipit ligula in lacus.'where comentario_id= 858;
update comentario set texto = 'Fusce consequat.'where comentario_id= 859;
update comentario set texto = 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'where comentario_id= 860;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 861;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 862;
update comentario set texto = 'Vivamus vel nulla eget eros elementum pellentesque.'where comentario_id= 863;
update comentario set texto = 'Sed accumsan felis.'where comentario_id= 864;
update comentario set texto = 'Maecenas ut massa quis augue luctus tincidunt.'where comentario_id= 865;
update comentario set texto = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'where comentario_id= 866;
update comentario set texto = 'Integer non velit.'where comentario_id= 867;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 868;
update comentario set texto = 'Morbi porttitor lorem id ligula.'where comentario_id= 869;
update comentario set texto = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'where comentario_id= 870;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 871;
update comentario set texto = 'In congue.'where comentario_id= 872;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 873;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 874;
update comentario set texto = 'Curabitur in libero ut massa volutpat convallis.'where comentario_id= 875;
update comentario set texto = 'Nulla justo.'where comentario_id= 876;
update comentario set texto = 'Phasellus id sapien in sapien iaculis congue.'where comentario_id= 877;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 878;
update comentario set texto = 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.'where comentario_id= 879;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 880;
update comentario set texto = 'Donec ut dolor.'where comentario_id= 881;
update comentario set texto = 'Nullam sit amet turpis elementum ligula vehicula consequat.'where comentario_id= 882;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 883;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 884;
update comentario set texto = 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'where comentario_id= 885;
update comentario set texto = 'Mauris lacinia sapien quis libero.'where comentario_id= 886;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 887;
update comentario set texto = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'where comentario_id= 888;
update comentario set texto = 'Nam dui.'where comentario_id= 889;
update comentario set texto = 'Phasellus sit amet erat.'where comentario_id= 890;
update comentario set texto = 'Mauris ullamcorper purus sit amet nulla.'where comentario_id= 891;
update comentario set texto = 'Etiam faucibus cursus urna.'where comentario_id= 892;
update comentario set texto = 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'where comentario_id= 893;
update comentario set texto = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'where comentario_id= 894;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 895;
update comentario set texto = 'Nullam porttitor lacus at turpis.'where comentario_id= 896;
update comentario set texto = 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.'where comentario_id= 897;
update comentario set texto = 'Nam dui.'where comentario_id= 898;
update comentario set texto = 'Nunc nisl.'where comentario_id= 899;
update comentario set texto = 'Nulla tellus.'where comentario_id= 900;
update comentario set texto = 'Duis mattis egestas metus.'where comentario_id= 901;
update comentario set texto = 'Integer non velit.'where comentario_id= 902;
update comentario set texto = 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'where comentario_id= 903;
update comentario set texto = 'Phasellus id sapien in sapien iaculis congue.'where comentario_id= 904;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 905;
update comentario set texto = 'Donec vitae nisi.'where comentario_id= 906;
update comentario set texto = 'Nulla tempus.'where comentario_id= 907;
update comentario set texto = 'Vivamus vestibulum sagittis sapien.'where comentario_id= 908;
update comentario set texto = 'Nulla justo.'where comentario_id= 909;
update comentario set texto = 'Morbi porttitor lorem id ligula.'where comentario_id= 910;
update comentario set texto = 'Donec posuere metus vitae ipsum.'where comentario_id= 911;
update comentario set texto = 'Vestibulum ac est lacinia nisi venenatis tristique.'where comentario_id= 912;
update comentario set texto = 'In congue.'where comentario_id= 913;
update comentario set texto = 'Duis ac nibh.'where comentario_id= 914;
update comentario set texto = 'Duis aliquam convallis nunc.'where comentario_id= 915;
update comentario set texto = 'Quisque porta volutpat erat.'where comentario_id= 916;
update comentario set texto = 'Nulla nisl.'where comentario_id= 917;
update comentario set texto = 'Cras in purus eu magna vulputate luctus.'where comentario_id= 918;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 919;
update comentario set texto = 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.'where comentario_id= 920;
update comentario set texto = 'Integer a nibh.'where comentario_id= 921;
update comentario set texto = 'In congue.'where comentario_id= 922;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 923;
update comentario set texto = 'Praesent id massa id nisl venenatis lacinia.'where comentario_id= 924;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 925;
update comentario set texto = 'Donec ut mauris eget massa tempor convallis.'where comentario_id= 926;
update comentario set texto = 'Aenean auctor gravida sem.'where comentario_id= 927;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 928;
update comentario set texto = 'Nullam varius.'where comentario_id= 929;
update comentario set texto = 'Aenean lectus.'where comentario_id= 930;
update comentario set texto = 'Nunc purus.'where comentario_id= 931;
update comentario set texto = 'Duis mattis egestas metus.'where comentario_id= 932;
update comentario set texto = 'Sed sagittis.'where comentario_id= 933;
update comentario set texto = 'Mauris sit amet eros.'where comentario_id= 934;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 935;
update comentario set texto = 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'where comentario_id= 936;
update comentario set texto = 'Duis bibendum.'where comentario_id= 937;
update comentario set texto = 'Morbi a ipsum.'where comentario_id= 938;
update comentario set texto = 'Pellentesque eget nunc.'where comentario_id= 939;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 940;
update comentario set texto = 'Pellentesque at nulla.'where comentario_id= 941;
update comentario set texto = 'Proin at turpis a pede posuere nonummy.'where comentario_id= 942;
update comentario set texto = 'Nulla facilisi.'where comentario_id= 943;
update comentario set texto = 'Nam nulla.'where comentario_id= 944;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 945;
update comentario set texto = 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'where comentario_id= 946;
update comentario set texto = 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'where comentario_id= 947;
update comentario set texto = 'Nunc purus.'where comentario_id= 948;
update comentario set texto = 'Morbi vel lectus in quam fringilla rhoncus.'where comentario_id= 949;
update comentario set texto = 'Nulla ut erat id mauris vulputate elementum.'where comentario_id= 950;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 951;
update comentario set texto = 'Aenean lectus.'where comentario_id= 952;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 953;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 954;
update comentario set texto = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'where comentario_id= 955;
update comentario set texto = 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'where comentario_id= 956;
update comentario set texto = 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'where comentario_id= 957;
update comentario set texto = 'In congue.'where comentario_id= 958;
update comentario set texto = 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.'where comentario_id= 959;
update comentario set texto = 'Duis ac nibh.'where comentario_id= 960;
update comentario set texto = 'Integer tincidunt ante vel ipsum.'where comentario_id= 961;
update comentario set texto = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'where comentario_id= 962;
update comentario set texto = 'Proin risus.'where comentario_id= 963;
update comentario set texto = 'In hac habitasse platea dictumst.'where comentario_id= 964;
update comentario set texto = 'Phasellus in felis.'where comentario_id= 965;
update comentario set texto = 'Suspendisse accumsan tortor quis turpis.'where comentario_id= 966;
update comentario set texto = 'Sed ante.'where comentario_id= 967;
update comentario set texto = 'Aliquam sit amet diam in magna bibendum imperdiet.'where comentario_id= 968;
update comentario set texto = 'Phasellus in felis.'where comentario_id= 969;
update comentario set texto = 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'where comentario_id= 970;
update comentario set texto = 'Praesent blandit.'where comentario_id= 971;
update comentario set texto = 'Morbi non quam nec dui luctus rutrum.'where comentario_id= 972;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 973;
update comentario set texto = 'Quisque id justo sit amet sapien dignissim vestibulum.'where comentario_id= 974;
update comentario set texto = 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.'where comentario_id= 975;
update comentario set texto = 'Ut tellus.'where comentario_id= 976;
update comentario set texto = 'Duis mattis egestas metus.'where comentario_id= 977;
update comentario set texto = 'Nulla suscipit ligula in lacus.'where comentario_id= 978;
update comentario set texto = 'Nunc nisl.'where comentario_id= 979;
update comentario set texto = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'where comentario_id= 980;
update comentario set texto = 'Maecenas rhoncus aliquam lacus.'where comentario_id= 981;
update comentario set texto = 'Sed ante.'where comentario_id= 982;
update comentario set texto = 'Maecenas pulvinar lobortis est.'where comentario_id= 983;
update comentario set texto = 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'where comentario_id= 984;
update comentario set texto = 'In sagittis dui vel nisl.'where comentario_id= 985;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.'where comentario_id= 986;
update comentario set texto = 'Praesent lectus.'where comentario_id= 987;
update comentario set texto = 'Donec ut dolor.'where comentario_id= 988;
update comentario set texto = 'Fusce consequat.'where comentario_id= 989;
update comentario set texto = 'Donec vitae nisi.'where comentario_id= 990;
update comentario set texto = 'Vestibulum rutrum rutrum neque.'where comentario_id= 991;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 992;
update comentario set texto = 'Maecenas ut massa quis augue luctus tincidunt.'where comentario_id= 993;
update comentario set texto = 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.'where comentario_id= 994;
update comentario set texto = 'Pellentesque ultrices mattis odio.'where comentario_id= 995;
update comentario set texto = 'Nullam molestie nibh in lectus.'where comentario_id= 996;
update comentario set texto = 'Duis aliquam convallis nunc.'where comentario_id= 997;
update comentario set texto = 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'where comentario_id= 998;
update comentario set texto = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'where comentario_id= 999;
update comentario set texto = 'Suspendisse potenti.'where comentario_id= 1000;
commit;



connect admin_contenido/admin_contenido
update seccion set contenido=fx_carga_blob('DIR_TMP','blob'||round(dbms_random.value(1,10))||'.mp3') where seccion_id=1;
update seccion set contenido=fx_carga_blob('DIR_TMP','blob'||round(dbms_random.value(1,10))||'.mp3') where seccion_id=2;
update seccion set contenido=fx_carga_blob('DIR_TMP','blob'||round(dbms_random.value(1,10))||'.mp3') where seccion_id=3;
update seccion set contenido=fx_carga_blob('DIR_TMP','blob'||round(dbms_random.value(1,10))||'.mp3') where seccion_id=4;
update seccion set contenido=fx_carga_blob('DIR_TMP','blob'||round(dbms_random.value(1,10))||'.mp3') where seccion_id=5;
commit;
