insert into audio (contenido_id, letra, formato, kbps) values (1, 'Praesent blandit.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (2, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (4, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (5, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (6, 'Proin interdum mauris non ligula pellentesque ultrices.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (7, 'Etiam pretium iaculis justo.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (8, 'Vivamus vestibulum sagittis sapien.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (9, 'Etiam pretium iaculis justo.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (10, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (11, 'Aliquam non mauris.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (12, 'Pellentesque viverra pede ac diam.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (13, 'Duis aliquam convallis nunc.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (14, 'Praesent id massa id nisl venenatis lacinia.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (15, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (16, 'Nam nulla.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (17, 'Aliquam non mauris.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (18, 'Curabitur at ipsum ac tellus semper interdum.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (19, 'In eleifend quam a odio.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (20, 'Duis bibendum.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (21, 'Maecenas rhoncus aliquam lacus.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (22, 'Duis at velit eu est congue elementum.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (23, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (24, 'Vestibulum ac est lacinia nisi venenatis tristique.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (25, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (26, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (27, 'Cras pellentesque volutpat dui.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (28, 'Vivamus vestibulum sagittis sapien.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (29, 'Etiam vel augue.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (30, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (31, 'Vivamus in felis eu sapien cursus vestibulum.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (32, 'Maecenas rhoncus aliquam lacus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (33, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (34, 'Duis bibendum.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (35, 'Morbi quis tortor id nulla ultrices aliquet.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (36, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (37, 'Aliquam sit amet diam in magna bibendum imperdiet.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (38, 'Sed vel enim sit amet nunc viverra dapibus.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (39, 'Maecenas tincidunt lacus at velit.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (40, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (41, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (42, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (43, 'Duis ac nibh.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (44, 'Quisque ut erat.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (45, 'Fusce consequat.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (46, 'In sagittis dui vel nisl.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (47, 'Morbi non quam nec dui luctus rutrum.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (48, 'Cras pellentesque volutpat dui.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (49, 'Aenean lectus.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (50, 'Integer non velit.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (51, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (52, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (53, 'Nulla tellus.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (54, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (55, 'Nulla ut erat id mauris vulputate elementum.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (56, 'Vestibulum ac est lacinia nisi venenatis tristique.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (57, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (58, 'Donec posuere metus vitae ipsum.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (59, 'Phasellus sit amet erat.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (60, 'Curabitur in libero ut massa volutpat convallis.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (61, 'Vivamus in felis eu sapien cursus vestibulum.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (62, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (63, 'Etiam pretium iaculis justo.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (64, 'In sagittis dui vel nisl.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (65, 'Donec ut dolor.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (66, 'Morbi non lectus.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (67, 'Nulla facilisi.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (68, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (69, 'Fusce consequat.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (70, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (71, 'Donec ut dolor.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (72, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (73, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (74, 'Suspendisse potenti.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (75, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (76, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (77, 'Donec posuere metus vitae ipsum.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (78, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (79, 'Maecenas pulvinar lobortis est.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (80, 'Cras non velit nec nisi vulputate nonummy.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (81, 'Donec dapibus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (82, 'Duis ac nibh.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (83, 'Nulla facilisi.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (84, 'Duis mattis egestas metus.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (85, 'In quis justo.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (86, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (87, 'Curabitur in libero ut massa volutpat convallis.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (88, 'Sed accumsan felis.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (89, 'In hac habitasse platea dictumst.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (90, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (91, 'Maecenas ut massa quis augue luctus tincidunt.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (92, 'Nulla justo.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (93, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (94, 'Donec vitae nisi.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (95, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (96, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (97, 'Phasellus sit amet erat.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (98, 'Nunc purus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (99, 'Quisque ut erat.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (100, 'Nulla suscipit ligula in lacus.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (101, 'Fusce consequat.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (102, 'Integer a nibh.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (103, 'Morbi non lectus.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (104, 'Integer ac leo.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (105, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (106, 'Ut at dolor quis odio consequat varius.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (107, 'Mauris sit amet eros.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (108, 'Integer non velit.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (109, 'Cras in purus eu magna vulputate luctus.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (110, 'Morbi non lectus.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (111, 'Duis bibendum.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (112, 'Vivamus vel nulla eget eros elementum pellentesque.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (113, 'Duis mattis egestas metus.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (114, 'Suspendisse potenti.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (115, 'Duis consequat dui nec nisi volutpat eleifend.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (116, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (117, 'Pellentesque eget nunc.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (118, 'Quisque ut erat.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (119, 'Cras non velit nec nisi vulputate nonummy.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (120, 'Sed sagittis.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (121, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (122, 'Donec dapibus.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (123, 'In hac habitasse platea dictumst.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (124, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (125, 'In blandit ultrices enim.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (126, 'Donec vitae nisi.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (127, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (128, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (129, 'Praesent id massa id nisl venenatis lacinia.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (130, 'Vivamus vel nulla eget eros elementum pellentesque.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (131, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (132, 'Curabitur convallis.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (133, 'Sed ante.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (134, 'Cras non velit nec nisi vulputate nonummy.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (135, 'Praesent blandit lacinia erat.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (136, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (137, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (138, 'Donec ut dolor.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (139, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (140, 'Ut tellus.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (141, 'Aenean sit amet justo.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (142, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (143, 'In hac habitasse platea dictumst.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (144, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (145, 'Maecenas rhoncus aliquam lacus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (146, 'Curabitur in libero ut massa volutpat convallis.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (147, 'Cras in purus eu magna vulputate luctus.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (148, 'Proin eu mi.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (149, 'Mauris sit amet eros.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (150, 'Aliquam erat volutpat.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (151, 'Duis aliquam convallis nunc.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (152, 'Vestibulum sed magna at nunc commodo placerat.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (153, 'Morbi porttitor lorem id ligula.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (154, 'Nulla ac enim.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (155, 'Donec semper sapien a libero.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (156, 'In hac habitasse platea dictumst.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (157, 'Proin eu mi.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (158, 'Sed vel enim sit amet nunc viverra dapibus.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (159, 'Nulla nisl.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (160, 'Aenean lectus.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (161, 'Donec ut dolor.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (162, 'In hac habitasse platea dictumst.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (163, 'Nulla suscipit ligula in lacus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (164, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (165, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (166, 'Duis at velit eu est congue elementum.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (167, 'Suspendisse ornare consequat lectus.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (168, 'Praesent lectus.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (169, 'Nulla justo.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (170, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (171, 'Pellentesque at nulla.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (172, 'Suspendisse potenti.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (173, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (174, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (175, 'Cras in purus eu magna vulputate luctus.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (176, 'Fusce consequat.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (177, 'Nulla facilisi.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (178, 'Pellentesque viverra pede ac diam.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (179, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (180, 'Duis consequat dui nec nisi volutpat eleifend.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (181, 'Vivamus vel nulla eget eros elementum pellentesque.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (182, 'Morbi non lectus.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (183, 'Pellentesque at nulla.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (184, 'Integer ac neque.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (185, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (186, 'Curabitur in libero ut massa volutpat convallis.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (187, 'Integer ac neque.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (188, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (189, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (190, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (191, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (192, 'Nunc nisl.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (193, 'Quisque ut erat.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (194, 'Sed accumsan felis.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (195, 'Cras pellentesque volutpat dui.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (196, 'Aenean fermentum.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (197, 'Sed ante.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (198, 'Duis bibendum.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (199, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (200, 'Aliquam quis turpis eget elit sodales scelerisque.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (201, 'Aliquam quis turpis eget elit sodales scelerisque.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (202, 'Donec quis orci eget orci vehicula condimentum.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (203, 'In hac habitasse platea dictumst.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (204, 'Pellentesque at nulla.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (205, 'Sed vel enim sit amet nunc viverra dapibus.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (206, 'Maecenas rhoncus aliquam lacus.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (207, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (208, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (209, 'Cras in purus eu magna vulputate luctus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (210, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (211, 'Nullam molestie nibh in lectus.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (212, 'Maecenas ut massa quis augue luctus tincidunt.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (213, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (214, 'Pellentesque eget nunc.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (215, 'Aliquam non mauris.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (216, 'Nulla justo.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (217, 'Integer tincidunt ante vel ipsum.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (218, 'Nam dui.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (219, 'Integer ac neque.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (220, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (221, 'Nulla justo.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (222, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (223, 'Vivamus tortor.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (224, 'Pellentesque viverra pede ac diam.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (225, 'Nam dui.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (226, 'Pellentesque viverra pede ac diam.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (227, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (228, 'Fusce consequat.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (229, 'Maecenas rhoncus aliquam lacus.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (230, 'Duis ac nibh.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (231, 'Praesent id massa id nisl venenatis lacinia.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (232, 'Morbi porttitor lorem id ligula.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (233, 'Mauris ullamcorper purus sit amet nulla.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (234, 'Aenean auctor gravida sem.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (235, 'Suspendisse potenti.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (236, 'Pellentesque at nulla.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (237, 'Nunc nisl.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (238, 'Aliquam sit amet diam in magna bibendum imperdiet.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (239, 'Suspendisse accumsan tortor quis turpis.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (240, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (241, 'Pellentesque ultrices mattis odio.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (242, 'Nullam molestie nibh in lectus.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (243, 'Maecenas tincidunt lacus at velit.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (244, 'Proin risus.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (245, 'Praesent lectus.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (246, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (247, 'Sed vel enim sit amet nunc viverra dapibus.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (248, 'Phasellus sit amet erat.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (249, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (250, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (251, 'Etiam pretium iaculis justo.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (252, 'Cras non velit nec nisi vulputate nonummy.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (253, 'Nulla facilisi.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (254, 'Nulla ac enim.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (255, 'Nulla justo.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (256, 'Vivamus vestibulum sagittis sapien.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (257, 'Praesent blandit lacinia erat.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (258, 'Duis at velit eu est congue elementum.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (259, 'Suspendisse potenti.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (260, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (261, 'Cras non velit nec nisi vulputate nonummy.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (262, 'Maecenas ut massa quis augue luctus tincidunt.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (263, 'Morbi non quam nec dui luctus rutrum.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (264, 'Integer non velit.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (265, 'Sed accumsan felis.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (266, 'Morbi non lectus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (267, 'Aenean auctor gravida sem.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (268, 'Ut tellus.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (269, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (270, 'Suspendisse ornare consequat lectus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (271, 'In hac habitasse platea dictumst.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (272, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (273, 'Proin interdum mauris non ligula pellentesque ultrices.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (274, 'In hac habitasse platea dictumst.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (275, 'Fusce consequat.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (276, 'Pellentesque viverra pede ac diam.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (277, 'Aliquam non mauris.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (278, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (279, 'Vivamus in felis eu sapien cursus vestibulum.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (280, 'Duis aliquam convallis nunc.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (281, 'Sed vel enim sit amet nunc viverra dapibus.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (282, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (283, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (284, 'Praesent blandit.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (285, 'Vestibulum ac est lacinia nisi venenatis tristique.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (286, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (287, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (288, 'Curabitur at ipsum ac tellus semper interdum.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (289, 'Maecenas ut massa quis augue luctus tincidunt.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (290, 'In hac habitasse platea dictumst.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (291, 'Suspendisse potenti.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (292, 'Sed sagittis.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (293, 'Nam nulla.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (294, 'Phasellus in felis.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (295, 'Suspendisse ornare consequat lectus.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (296, 'Morbi non lectus.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (297, 'Vivamus in felis eu sapien cursus vestibulum.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (298, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (299, 'In hac habitasse platea dictumst.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (300, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (301, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (302, 'Proin risus.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (303, 'Nulla facilisi.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (304, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (305, 'Sed vel enim sit amet nunc viverra dapibus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (306, 'Maecenas ut massa quis augue luctus tincidunt.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (307, 'Duis mattis egestas metus.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (308, 'In eleifend quam a odio.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (309, 'Aliquam erat volutpat.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (310, 'Etiam justo.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (311, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (312, 'Nullam molestie nibh in lectus.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (313, 'Mauris sit amet eros.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (314, 'In hac habitasse platea dictumst.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (315, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (316, 'In hac habitasse platea dictumst.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (317, 'Morbi non quam nec dui luctus rutrum.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (318, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (319, 'Cras non velit nec nisi vulputate nonummy.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (320, 'Quisque ut erat.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (321, 'In quis justo.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (322, 'Nam tristique tortor eu pede.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (323, 'Nulla ac enim.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (324, 'Nam dui.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (325, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (326, 'In hac habitasse platea dictumst.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (327, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (328, 'Proin risus.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (329, 'Suspendisse potenti.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (330, 'Suspendisse accumsan tortor quis turpis.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (331, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (332, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (333, 'Proin eu mi.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (334, 'Morbi non lectus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (335, 'Integer non velit.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (336, 'Quisque ut erat.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (337, 'In congue.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (338, 'Duis at velit eu est congue elementum.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (339, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (340, 'Suspendisse potenti.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (341, 'Nullam varius.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (342, 'Curabitur at ipsum ac tellus semper interdum.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (343, 'Morbi a ipsum.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (344, 'Praesent id massa id nisl venenatis lacinia.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (345, 'Nulla ut erat id mauris vulputate elementum.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (346, 'Integer a nibh.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (347, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (348, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (349, 'Donec dapibus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (350, 'Duis aliquam convallis nunc.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (351, 'Sed vel enim sit amet nunc viverra dapibus.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (352, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (353, 'Pellentesque eget nunc.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (354, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (355, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (356, 'Donec ut dolor.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (357, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (358, 'Vivamus vestibulum sagittis sapien.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (359, 'Etiam faucibus cursus urna.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (360, 'Nulla tellus.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (361, 'Suspendisse potenti.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (362, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (363, 'Maecenas ut massa quis augue luctus tincidunt.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (364, 'Duis mattis egestas metus.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (365, 'Donec dapibus.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (366, 'Praesent blandit lacinia erat.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (367, 'Maecenas tincidunt lacus at velit.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (368, 'Mauris sit amet eros.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (369, 'Aliquam non mauris.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (370, 'In quis justo.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (371, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (372, 'Integer a nibh.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (373, 'In sagittis dui vel nisl.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (374, 'In quis justo.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (375, 'Nulla suscipit ligula in lacus.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (376, 'Maecenas ut massa quis augue luctus tincidunt.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (377, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (378, 'Nam tristique tortor eu pede.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (379, 'Nullam varius.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (380, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (381, 'Suspendisse potenti.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (382, 'Nunc rhoncus dui vel sem.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (383, 'Donec semper sapien a libero.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (384, 'Nulla nisl.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (385, 'Curabitur in libero ut massa volutpat convallis.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (386, 'Mauris ullamcorper purus sit amet nulla.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (387, 'Phasellus sit amet erat.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (388, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (389, 'Donec dapibus.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (390, 'In hac habitasse platea dictumst.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (391, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (392, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (393, 'Vivamus tortor.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (394, 'Vivamus in felis eu sapien cursus vestibulum.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (395, 'Duis aliquam convallis nunc.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (396, 'In hac habitasse platea dictumst.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (397, 'Donec dapibus.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (398, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (399, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (400, 'Morbi non quam nec dui luctus rutrum.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (401, 'Praesent id massa id nisl venenatis lacinia.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (402, 'Pellentesque ultrices mattis odio.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (403, 'Quisque ut erat.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (404, 'Nulla facilisi.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (405, 'Morbi a ipsum.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (406, 'Proin risus.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (407, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (408, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (409, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (410, 'Nullam molestie nibh in lectus.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (411, 'Duis ac nibh.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (412, 'Nulla tempus.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (413, 'Donec ut dolor.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (414, 'Sed ante.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (415, 'Nulla nisl.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (416, 'Etiam pretium iaculis justo.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (417, 'Donec ut mauris eget massa tempor convallis.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (418, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (419, 'Aliquam non mauris.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (420, 'Pellentesque eget nunc.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (421, 'Morbi a ipsum.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (422, 'Vestibulum ac est lacinia nisi venenatis tristique.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (423, 'Proin interdum mauris non ligula pellentesque ultrices.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (424, 'Donec ut mauris eget massa tempor convallis.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (425, 'Nulla tellus.', 'wav', 128);
insert into audio (contenido_id, letra, formato, kbps) values (426, 'Duis ac nibh.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (427, 'In congue.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (428, 'Aliquam quis turpis eget elit sodales scelerisque.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (429, 'Integer non velit.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (430, 'Praesent blandit.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (431, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (432, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (433, 'In hac habitasse platea dictumst.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (434, 'Nunc purus.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (435, 'Morbi non lectus.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (436, 'Aenean auctor gravida sem.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (437, 'Nulla justo.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (438, 'Maecenas ut massa quis augue luctus tincidunt.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (439, 'Vestibulum rutrum rutrum neque.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (440, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (441, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (442, 'Integer non velit.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (443, 'Duis bibendum.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (444, 'Morbi a ipsum.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (445, 'Proin eu mi.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (446, 'Duis at velit eu est congue elementum.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (447, 'Nulla ut erat id mauris vulputate elementum.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (448, 'Nam nulla.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (449, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'mp3', 96);
insert into audio (contenido_id, letra, formato, kbps) values (450, 'Curabitur in libero ut massa volutpat convallis.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (451, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (452, 'In congue.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (453, 'Etiam pretium iaculis justo.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (454, 'Aliquam non mauris.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (455, 'In eleifend quam a odio.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (456, 'Phasellus sit amet erat.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (457, 'Donec dapibus.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (458, 'Pellentesque ultrices mattis odio.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (459, 'Morbi ut odio.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (460, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (461, 'Quisque porta volutpat erat.', 'ogg', 96);
insert into audio (contenido_id, letra, formato, kbps) values (462, 'Donec quis orci eget orci vehicula condimentum.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (463, 'In hac habitasse platea dictumst.', 'wav', 320);
insert into audio (contenido_id, letra, formato, kbps) values (464, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'wav', 160);
insert into audio (contenido_id, letra, formato, kbps) values (465, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (466, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (467, 'Morbi ut odio.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (468, 'Nulla ut erat id mauris vulputate elementum.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (469, 'Morbi porttitor lorem id ligula.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (470, 'In quis justo.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (471, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'ogg', 320);
insert into audio (contenido_id, letra, formato, kbps) values (472, 'In hac habitasse platea dictumst.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (473, 'Morbi non quam nec dui luctus rutrum.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (474, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'mp3', 160);
insert into audio (contenido_id, letra, formato, kbps) values (475, 'Proin at turpis a pede posuere nonummy.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (476, 'In hac habitasse platea dictumst.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (477, 'Fusce posuere felis sed lacus.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (478, 'Nulla tellus.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (479, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (480, 'Integer tincidunt ante vel ipsum.', 'ogg', 256);
insert into audio (contenido_id, letra, formato, kbps) values (481, 'Donec semper sapien a libero.', 'ogg', 160);
insert into audio (contenido_id, letra, formato, kbps) values (482, 'Maecenas pulvinar lobortis est.', 'wav', 96);
insert into audio (contenido_id, letra, formato, kbps) values (483, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (484, 'Morbi quis tortor id nulla ultrices aliquet.', 'mp3', 128);
insert into audio (contenido_id, letra, formato, kbps) values (485, 'Nam dui.', 'flac', 96);
insert into audio (contenido_id, letra, formato, kbps) values (486, 'Nulla tempus.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (487, 'Duis aliquam convallis nunc.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (488, 'Etiam pretium iaculis justo.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (489, 'Pellentesque at nulla.', 'flac', 256);
insert into audio (contenido_id, letra, formato, kbps) values (490, 'Aenean sit amet justo.', 'flac', 320);
insert into audio (contenido_id, letra, formato, kbps) values (491, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'flac', 160);
insert into audio (contenido_id, letra, formato, kbps) values (492, 'Suspendisse potenti.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (493, 'Aenean fermentum.', 'flac', 128);
insert into audio (contenido_id, letra, formato, kbps) values (494, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (495, 'Duis ac nibh.', 'ogg', 128);
insert into audio (contenido_id, letra, formato, kbps) values (496, 'Curabitur at ipsum ac tellus semper interdum.', 'wav', 256);
insert into audio (contenido_id, letra, formato, kbps) values (497, 'Pellentesque at nulla.', 'mp3', 320);
insert into audio (contenido_id, letra, formato, kbps) values (498, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (499, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'mp3', 256);
insert into audio (contenido_id, letra, formato, kbps) values (500, 'Etiam justo.', 'ogg', 160);

