insert into genero (genero_id, nombre, descripcion) values (1, 'Horror', 'Donec vitae nisi.');
insert into genero (genero_id, nombre, descripcion) values (2, 'Action|Comedy|Crime|Thriller', 'In eleifend quam a odio.');
insert into genero (genero_id, nombre, descripcion) values (3, 'Horror|Thriller', 'Integer ac neque.');
insert into genero (genero_id, nombre, descripcion) values (4, 'Comedy', 'Morbi ut odio.');
insert into genero (genero_id, nombre, descripcion) values (5, 'Drama|Romance', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into genero (genero_id, nombre, descripcion) values (6, 'Documentary', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into genero (genero_id, nombre, descripcion) values (7, 'Comedy', 'Pellentesque ultrices mattis odio.');
insert into genero (genero_id, nombre, descripcion) values (8, 'Adventure|Comedy', 'Maecenas tincidunt lacus at velit.');
insert into genero (genero_id, nombre, descripcion) values (9, 'Crime|Thriller', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into genero (genero_id, nombre, descripcion) values (10, 'Comedy', 'Mauris ullamcorper purus sit amet nulla.');
insert into genero (genero_id, nombre, descripcion) values (11, 'Children|Comedy', 'Suspendisse accumsan tortor quis turpis.');
insert into genero (genero_id, nombre, descripcion) values (12, 'Drama|Mystery', 'Sed sagittis.');
insert into genero (genero_id, nombre, descripcion) values (13, 'Comedy|Drama', 'Praesent blandit lacinia erat.');
insert into genero (genero_id, nombre, descripcion) values (14, 'Drama', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into genero (genero_id, nombre, descripcion) values (15, 'Drama', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into genero (genero_id, nombre, descripcion) values (16, 'Comedy|Romance', 'Praesent blandit.');
insert into genero (genero_id, nombre, descripcion) values (17, 'Crime|Mystery|Thriller', 'In hac habitasse platea dictumst.');
insert into genero (genero_id, nombre, descripcion) values (18, 'Drama|Horror|Mystery', 'Mauris sit amet eros.');
insert into genero (genero_id, nombre, descripcion) values (19, 'Documentary', 'Etiam pretium iaculis justo.');
insert into genero (genero_id, nombre, descripcion) values (20, 'Comedy|Drama|Romance', 'Duis bibendum.');
insert into genero (genero_id, nombre, descripcion) values (21, 'Animation|Comedy', 'Fusce posuere felis sed lacus.');
insert into genero (genero_id, nombre, descripcion) values (22, 'Documentary', 'Proin risus.');
insert into genero (genero_id, nombre, descripcion) values (23, 'Drama', 'Mauris ullamcorper purus sit amet nulla.');
insert into genero (genero_id, nombre, descripcion) values (24, 'Drama', 'Quisque ut erat.');
insert into genero (genero_id, nombre, descripcion) values (25, 'Drama', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into genero (genero_id, nombre, descripcion) values (26, 'Adventure|Musical', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into genero (genero_id, nombre, descripcion) values (27, 'Comedy|Horror', 'Morbi porttitor lorem id ligula.');
insert into genero (genero_id, nombre, descripcion) values (28, 'Action|Drama|Romance|War', 'Maecenas rhoncus aliquam lacus.');
insert into genero (genero_id, nombre, descripcion) values (29, 'Comedy|Drama', 'Vestibulum sed magna at nunc commodo placerat.');
insert into genero (genero_id, nombre, descripcion) values (30, 'Documentary', 'Donec quis orci eget orci vehicula condimentum.');
insert into genero (genero_id, nombre, descripcion) values (31, 'Comedy|Fantasy|Romance', 'Curabitur at ipsum ac tellus semper interdum.');
insert into genero (genero_id, nombre, descripcion) values (32, 'Drama|War', 'Integer tincidunt ante vel ipsum.');
insert into genero (genero_id, nombre, descripcion) values (33, 'Action|Sci-Fi|Thriller', 'In hac habitasse platea dictumst.');
insert into genero (genero_id, nombre, descripcion) values (34, 'Drama', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into genero (genero_id, nombre, descripcion) values (35, 'Adventure|Drama|Sci-Fi', 'In sagittis dui vel nisl.');
insert into genero (genero_id, nombre, descripcion) values (36, 'Comedy|Documentary', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into genero (genero_id, nombre, descripcion) values (37, 'Comedy', 'In sagittis dui vel nisl.');
insert into genero (genero_id, nombre, descripcion) values (38, 'Drama', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into genero (genero_id, nombre, descripcion) values (39, 'Drama|Thriller', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into genero (genero_id, nombre, descripcion) values (40, 'Action|Drama', 'Donec ut mauris eget massa tempor convallis.');
insert into genero (genero_id, nombre, descripcion) values (41, 'Drama', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into genero (genero_id, nombre, descripcion) values (42, 'Drama|Mystery', 'Donec dapibus.');
insert into genero (genero_id, nombre, descripcion) values (43, 'Children|Comedy', 'Etiam vel augue.');
insert into genero (genero_id, nombre, descripcion) values (44, 'Drama|Romance', 'Donec dapibus.');
insert into genero (genero_id, nombre, descripcion) values (45, 'Adventure|Romance|War', 'In quis justo.');
insert into genero (genero_id, nombre, descripcion) values (46, 'Adventure', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into genero (genero_id, nombre, descripcion) values (47, 'Adventure|Drama|Romance', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into genero (genero_id, nombre, descripcion) values (48, 'Drama', 'Aenean auctor gravida sem.');
insert into genero (genero_id, nombre, descripcion) values (49, 'Horror|Thriller', 'Nam nulla.');
insert into genero (genero_id, nombre, descripcion) values (50, 'Documentary|War', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
